import { filmType } from "@prisma/client";
import { TypeToFilmTypeMap } from "./types/types";

export const columnHeaders = [
  "title",
  "japaneseTitle",
  "type",
  "score",
  "episodes",
  "startDate",
  "endDate",
  "rating",
  "categories",
  "themes",
  "bio",
  "imgPath",
  "trailerUrl",
];

export const approvedCategories = [
  "Supernatural",
  "Suspense",
  "Detective",
  "Psychological",
  "Drama",
  "Fantasy",
  "Action",
  "Adventure",
  "Historical",
  //   "Samurai",
  "Comedy",
  "Ecchi",
  "Romance",
  "Harem",
  "School",
  //   "CGDCT",
  "Mythology",
  //   "Otaku Culture",
  //   "Workplace",
  "Sports",
  //   "Team Sports",
  "Military",
  "Vampire",
  "Sci-Fi",
  "Super Power",
  "Martial Arts",
  "Horror",
  "Gore",
  "High Stakes Game",
  "Survival",
  //   "Anthropomorphic",
  "Mystery",
  "Isekai",
  //   "Delinquents",
  //   "Love Polygon",
  "Reverse Harem",
  //   "Award Winning",
  "Mecha",
  "Slice of Life",
  //   "Childcare",
  //   "Iyashikei",
  "Music",
  "Gourmet",
  "Parody",
  //   "Reincarnation",
  "Adult Cast",
  "Organized Crime",
  //   "Mahou Shoujo",
  //   "Combat Sports", // change to Sports
  "Boys Love",
  "Video Game",
  //   "Avant Garde",
  "Time Travel",
  //   "Romantic Subtext",
  "Strategy Game",
  //   "Performing Arts",
  //   "Gag Humor",
  "Erotica",
  "Girls Love",
  //   "Magical Sex Shift",
  "Space",
  "Visual Arts",
  //   "Crossdressing",
  //   "Showbiz",
  "Racing",
  "Educational",
  "Medical",
  //   "Idols (Female)",
];

export const filmTypeMap: TypeToFilmTypeMap = new Map([
  ["tv", filmType.TV],
  ["movie", filmType.Movie],
  ["ova", filmType.OVA],
  ["ona", filmType.ONA],
  ["special", filmType.Special],
]);
